### ISSUE TITLE
Pasting a GIT URL in the package explorer generates a wrong content. 

### ISSUE THREAD

**Issue by opcoach** [eclipse-egit/egit#48] opened 2024-08-09 10:12 UTC
### Version

6.10.0

### Operating System

MacOS

### Eclipse version

2024-06

### Bug description

I wanted to clone a GIT repository in my current Eclipse using the Copy/Paste command with a GIT URL in my clipboard and I got a wrong content ...

## Steps to reproduce

- Copy this URL (or any other git url) : git@github.com:eclipse-platform/eclipse.platform.ui.git
- Open the package explorer part 
- Paste inside the view

### Actual behavior

In the package explorer view I got this unrelevant result : 

![image](https://github.com/user-attachments/assets/d2516b8f-ffe1-4504-a50f-ecb1bbe143df)

In the project explorer view I got ... nothing ... 

### Expected behavior

whatever the 'explorer view' (project explorer view, package explorer view, cdt project view, I would say Common navigator view...) we should get the git clone dialog like in the git repository view.

![image](https://github.com/user-attachments/assets/3ad2066a-ac2f-41dc-9d0a-982870eb506a)

### Other information

Bug fix suggestion : The paste command should be intercepted (on the workbench or on the common navigator view) by egit and taken  only if the clipboard contains a text with a git URL pattern. When egit ui plugin starts, it should register its priority paste handler on the workbench... If the paste command is not for him, it passes to the next plugin...

**Comment by Bananeweizen** [comment] 2024-08-09 12:25
IMO that's not possible. https://github.com/eclipse-egit/egit/blob/e02244685a1ad24eb07a356f090231509bd04ae2/org.eclipse.egit.ui/src/org/eclipse/egit/ui/internal/repository/tree/command/PasteCommand.java#L56 is a command handler, and a handler cannot just intercept arbitrary other handlers already bound to a command somewhere else, or can it?

**Comment by opcoach** [comment] 2024-08-12 10:30
Yes we can may be change the active when condition in the handler definition as It is defined only for the repository view. 

![image](https://github.com/user-attachments/assets/f1a311ba-0c74-4f63-95a9-0a398224575b)

By adding an 'or' condition on other activePartID, that should work... 

I wil try it

**Comment by opcoach** [comment] 2024-08-19 22:36
I got it.. I will provide a solution for this bug using a new Property Tester focused on the clipboard content...

In my implementation I had to make the Git Repository View visible. Is it a problem ? It means that whatever the perspective displayed, the 'Git Repositories' will appear behind the dialog when pasting a 'git url' compliant text.  I tried to switch to the git perspective but it is more complicated. 

![image](https://github.com/user-attachments/assets/3f8aa856-dd51-4c74-b520-32a546a9ac01)

**Comment by tfroment** [comment] 2024-08-20 15:32
Thanks a lot @opcoach!

**Comment by msohn** [comment] 2024-08-20 15:34
You need to push your change to Gerrit at https://eclipse.gerrithub.io, GerritHub uses GitHub for authentication but otherwise it's a Gerrit server.

**Comment by opcoach** [comment] 2024-08-21 10:11
@msohn, I missed the step where I had to request the organization access to eclipse-egit when I signed in gerrithub (as explained in your contribution guide)... I assume the button simply sends an email to grant access... Could you please accept my login (opcoach), to eclipse-egit so that I can push my contribution to gerrithub ?

**Comment by msohn** [comment] 2024-08-21 14:41
This shouldn't be necessary since you are not an EGit committer

**Comment by msohn** [comment] 2024-08-29 13:29
> @msohn thank you. I commented my bug fixing journey in this issue : https://gitlab.eclipse.org/eclipse-wg/ide-wg/community/-/issues/53. Fell free to comment if needed...
> 
> I will try to push my patch now...
> 
> * I have checked the remote URL of the GIT repository : it is bound to gerrithub  -> Should be ok, and I assume I can push directly and that will create the 'change' on gerrithub.
> * The commit message format must contain the Commit-ID to contain the changes (it is provided in the installed IDE) -> should be ok.

The commit message must contain a "Change-Id:" commit message trailer in the last paragraph.
There is a button in the staging view to add it, when you enabled gerrit on this repo that should happen automatically.
When using git command line install the commit-msg hook, if you try to push without a Change-Id footer Gerrit will respond with instructions how to do that. If you clone using the "Clone URL with commit-msg hook" URL shown here https://eclipse.gerrithub.io/admin/repos/eclipse-egit/egit,general the commit-msg hook is installed automatically. 

> * I launched a mvn clean verify in the egit repository and it failed because egit and jgit are sibling  (org.apache.maven.InternalErrorException: Internal error: java.lang.RuntimeException: Failed to load p2 repository with ID 'jgit' from location file://Users/olivier/egit-master/git/egit/org.eclipse.egit/../../jgit/org.eclipse.jgit.packaging/org.eclipse.jgit.repository/target/repository) ...

For the maven build follow https://github.com/eclipse-egit/egit/wiki/Contributor-Guide#builds

> 
> I made a commit in a branch (fix48), over the current master (see below) :
> 
> 
> I have still some questions about the best practices to provide the patch.
> 
> * what are the other steps I could do locally before pushing ?

You can run and test it locally by starting a development IDE from Eclipse. See https://github.com/eclipse-egit/egit/wiki/Contributor-Guide#running-egit-from-eclipse

> * Is that ok to push it directly from eclipse ?

yes, first configure Gerrit for this repo following https://github.com/eclipse-egit/egit/wiki/User-Guide#working-with-gerrit
Then select the repo in the repositories view and click "Push to Gerrit..."

> * Is there still a 'Gerrit' plugin to install in Eclipse to manage changes (I used that some years ago...)...

There is some Gerrit integration included in EGit which you can enable as described above

> * The git remote URL is https://eclipse.gerrithub.io/eclipse-egit/egit, will it use my GitHub credentials ?

If Eclipse doesn't have credentials for GerritHub it will open a login dialog where you should enter your GitHub username and personal access token in the password field.

> * how can I bind my change to the corresponding issue in the comment ? Is it 'Fix-48' ?  (there is no template for that in the default commit message).

add a "Bug: egit-<issue id>" commit message trailer in the last paragraph of the commit message as explained in https://github.com/eclipse-egit/egit/wiki/Contributor-Guide#commit-message-guidelines

> 
> Other things :
> 
> * I didn't add the 'file header' voluntary to see if the review will reject my change

I don't understand what you mean by file header

> * I didn't add tests also to see if the review will reject it
> 
> Sorry to ask these simple questions but I am trying to find the easiest ways to contribute on Eclipse in general and to take the role of a real newbie (which I am actually on this project :)) ...

**Comment by tomaswolf** [comment] 2024-10-09 17:34
[Gerrit change 1200237](https://eclipse.gerrithub.io/c/eclipse-egit/egit/+/1200237) is merged. Thanks, Olivier!

**Closed by tomaswolf** 2024-10-09 17:34 UTC
Labels: enhancement

**Comment by iloveeclipse** [comment] 2025-03-11 14:47
This feature causes regressions, see https://github.com/eclipse-egit/egit/issues/83
