### ISSUE TITLE
Egit can't fetch from remote

### ISSUE THREAD

**Issue by nlisker** [eclipse-egit/egit#39] opened 2024-07-05 16:30 UTC
### Version

6.10

### Operating System

Windows

### Eclipse version

4.32

### Bug description

I updated from Eclipse 4.31 and Egit 6.9 to 4.32 and 6.10. In the Git Repositories view, right clicking a remote and selecting Fetch produces the error:

An internal error occurred during: Fetch from <repo name> - <remote name>
Class not found: org/slf4j/spi/LocationAwareLogger

Subsequent attempts complained about a different class not found: HttpClientSession

I since had to revert to Egit 6.9 (still on Eclipse 4.32) and the problem has been resolved there, so I don't have the full stack traces. If there's no direction of investigation, I could try to find the time to re-update, get the full log, and re-revert.

### Actual behavior

The above error message was given and no fetching happened.

### Expected behavior

Fetch should work normally.

### Other information

Looks similar to #5.

**Comment by 4javier** [comment] 2024-08-03 15:04
Issue confirmed on `SpringToolSuite 4.24.0.RELEASE` based on `Eclipse 4.33.0.v202407` and `eGit 7.0.0.20240710`
Solved switching from HTTP Client from "Apache" to "Java built-in" in "Remote Connections" pane from `Window → Preferences → Version Control (Team) → Git` menu.

**Comment by msohn** [comment] 2024-08-29 12:55
duplicate of #5

**Closed by msohn** 2024-08-29 12:55 UTC
Labels: bug, duplicate
